### ISSUE TITLE
Dictionary does not understand #jsonString

### ISSUE THREAD

**Issue by fxgallego** [rko281/GitHub#1]
In a clean image with the Dolphin latest commit, I tried to install Seaside.
After GitHub package manager asks my GitHub credentials the following message not understood is raised from `GitHubCredentials>>authorizeWithPassword:description:`
![image](https://user-images.githubusercontent.com/2080171/82941230-66e83600-9f6c-11ea-81cd-8c7877682d7a.png)

**Comment by rko281** [comment]
The issue was caused by the switch from the US JSON package to STONJSON; this area of code was missed and still references the old API.

I'll patch this up for now but given the deprecation of this mechanism I'll also attempt to replace it.
