### ISSUE TITLE
GitHub authorization deprecation notice

### ISSUE THREAD

**Issue by fxgallego** [rko281/GitHub#2]
GitHub send me this email when using GitHub package manager

Hi @fxgallego,

On May 26th, 2020 at 19:23 (UTC) you or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent fxgallego@gmail.com.

We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow

You can learn more about these changes by visiting our developer blog https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint

Thanks,
The GitHub Team

**Comment by fxgallego** [comment]
I wrote the json request by hand (due to #1) so maybe this is related to a malformed request.

**Comment by fxgallego** [comment]
Why I need authentication to download something that's public?
For example I can download this project at https://github.com/rko281/GitHub/archive/master.zip
I know that for private packages it makes sense but not for public ones.
Maybe we can add a special api for each purpose:
`GitHubPackageManager installPrivateRepo: 'rko281/MethodSpies/Method Spies'`
`GitHubPackageManager installPublicRepo: 'rko281/MethodSpies/Method Spies'`
you should decide which is de default for `#install:`, or maybe always try first download anonymous.
No other package managers ask for credentials so it's a bit strange to require it.

**Comment by rko281** [comment]
The authentication is purely to get around the non-authenticated GitHub API rate limit of 60 requests per hour. The GitHub Package Manager is quite chatty when tracing the prerequisite chain; for a large app like Seaside it will quickly exceed the unauthenticated request limit.

I could mitigate this by first downloading the whole target repository and tracing the prerequisites locally; there's usually only a handful which require further interrogating other repositories. I'll look into this as an alternative to implementing the new GitHub authentication token mechanism.

**Comment by fxgallego** [comment]
@rko281 Thanks!
I'm planing to use this to automatically download external dependencies in my builds, so no user interaction is possible. Also images are fresh all the times, so storing tokens in images isn't an option. Let me know if you need some help or testing.

**Comment by rko281** [comment]
GitHubPackageManager is now substantially rewritten to remove the use of the GitHub API, thus the authorization deprecation is no longer an issue.
