### ISSUE TITLE
Package loading issue

### ISSUE THREAD

**Issue by sanjayminni** [rko281/GitHub#3]
Cannot load package if Seaside is already loaded in Dolphin Image

**Comment by rko281** [comment]
Actually nothing to do with the GitHubPackageManager; corrupt prerequisite information in Bootstrap package.

**Comment by sanjayminni** [comment]
Do I need to report this anywhere or has the underlying issue been
resolved  ?

**Comment by rko281** [comment]
[It's now fixed](https://github.com/rko281/Seaside-Bootstrap4/commit/a886600f7347ccfa679e027537662a10c5c32e71)
