### ISSUE TITLE
Cannot install package from GitHub repository rko281/RESTClient

### ISSUE THREAD

**Issue by bernhardkohlhaas** [rko281/GitHub#4]
I've successfully tried the examples in your documentation ,e.g. "GitHubPackageManager install: 'rko281/MethodSpies/Method Spies'." works fine and loads the package files to location <smalltalk image dir>\Method Spies\<files> and installs from there. This seems to be a special case though, because the subdirectory name is the same as the stem of the pax file (and the same as the repository name).

However I haven't been able to load the package from repository rko281/RESTClient .  I tried the expression `GitHubPackageManager install: 'rko281/RESTClient/src/Rest Client'` and this causes a walkback in the block in GitHubPackageManager>>locateRootPackageFor:

![Dolphin Walkback](https://user-images.githubusercontent.com/16484211/215344497-25c24c3b-4c4d-4fda-b905-b5f4f0399639.jpg)

The reason is that parameter aString = '<smalltalk image dir>\RESTClient\src\Rest Client.pax' and repositoryPath = '<smalltalk image dir>\RESTClient\src\', but the zip files was extracted one directory up into '<smalltalk image dir>\RESTClient\'.

Two general remarks:

1. I'm not sure that the logic to pull the package files up one level (or perhaps even all levels into the repository root directory) is helping things. E.g. I'd rather have the package files at _smalltalk image dir_\RESTClient\src\' than at _smalltalk image dir_\RESTClient\' (or - using the "Method Spies" example - I'd rather have them at _smalltalk image dir_\Method Spies\Method Spies\' than at _smalltalk image dir_\Method Spies\'. 
This would mirror the github tree and avoid ambiguities. I don't see a practical downside to that, because the Dolphin System Browser and Package Manager anyway show a package when selecting any of the parent nodes. Thus you wouldn't need to drill down that extra level to the final leaf node.

2. The logic to determine the local directory a package gets downloaded to and installed from is spread out a bit. For example some of it happens in GitHubBranch>>download and GitHubBranch>>download: (perhaps even GitHubBranch>>downloadArchive: ) and some of it in GitHubPackageManager install:branch:. 

E.g. both places hardcode the local download location as <smalltalk image dir>/<github repository name>. 

IMHO that logic should be in a single place, probably best in class GitHubBranch, since that would provide maximum flexibility in case someone tries to implement a different logic.

My initial motivation to dig deeper into this package was to change the download location to something like <smalltalk image dir>/github/<github user>/<github repository name> , but that meant changing this logic in multiple places. And when subclassing each of class GitHubRepository, GitHubPackageManager, and GitHubBranch I had to overwrite several access methods where the class names for GitHubRepository and GitHubBranch were hard-coded.

On that note perhaps having (and using) methods GitHubPackageManager>>repositoryClass and GitHubRepository>>branchClass would come in handy here.

In any case thank you so much for providing this repository. For me it is a great source of many insights into how to write better Smalltalk code and how to approach certain problems.

**Comment by bernhardkohlhaas** [comment]
Update: After some further research I found that `GitHubPackageManager install: 'bernhardkohlhaas/BKRESTClient/level1/level2/Rest Client'` actually works and puts the package in the correct path at _smalltalk image dir_\BKRESTClient\level1\level2\REST Client.pax_ without skipping a directory level.

So the error when evaluating `GitHubPackageManager install: 'rko281/RESTClient/src/Rest Client` might be due to the special handling of the _src_ directory.

**Comment by rko281** [comment]
Hi Bernard - thanks for your thoughts on the general code organisation - I'll take a look at this when I have time. 

To address your original issue, the correct invocation for loading the REST Client direct from GitHub is:

```smalltalk
GitHubPackageManager install: 'rko281/RESTClient'
```

The general rule is that where the repository name matches the package name (with allowances for the lack of spaces in repository names) the package name can be omitted. Further, the `src` directory in the GitHub repository is purely for organisational convenience (to avoid cluttering the repository page with possibly a large number of files) and is omitted by the GitHubPackageManager when creating the local directory structure. Thus the following is also valid:

```smalltalk
GitHubPackageManager install: 'rko281/RESTClient/Rest Client'.
````

A (deprecated) alternative to using `src` for organisation is to use a directory with the same name as the repository - see e.g. rko281/ReStore. Note this must be the only package-containing directory in the root of the repository. 

It's possible to nest package files deeper in a repository by using a directory name other than `src` or the repository name (or in the latter case, to also include other package-containing directories - see rko281/Seaside).
